from pathlib import Path

from app import create_app
from extensions import db
from models.comment import Comment
from models.post import Post
from models.story import Story
from models.user import User
from utils.image_handler import ensure_upload_structure


SAMPLE_USERS = [
    {
        "username": "santa",
        "email": "santa@neurality.dev",
        "password": "northpole123",
        "bio": "Delivering joy, one post at a time.",
        "accent": ("#D7263D", "#F4A261"),
    },
    {
        "username": "ginger",
        "email": "ginger@neurality.dev",
        "password": "cookies123",
        "bio": "Cookie reviews and workshop behind the scenes.",
        "accent": ("#2A9D8F", "#F4E285"),
    },
    {
        "username": "blitzen",
        "email": "blitzen@neurality.dev",
        "password": "reindeer123",
        "bio": "Fast flights, frosty skies, and quiet mornings.",
        "accent": ("#264653", "#8AB17D"),
    },
]


def write_svg(path: Path, label: str, start: str, end: str):
    svg = f"""<svg xmlns="http://www.w3.org/2000/svg" width="1200" height="1200" viewBox="0 0 1200 1200">
  <defs>
    <linearGradient id="bg" x1="0%" y1="0%" x2="100%" y2="100%">
      <stop offset="0%" stop-color="{start}" />
      <stop offset="100%" stop-color="{end}" />
    </linearGradient>
  </defs>
  <rect width="1200" height="1200" fill="url(#bg)" rx="80" />
  <circle cx="920" cy="220" r="160" fill="rgba(255,255,255,0.16)" />
  <circle cx="260" cy="940" r="220" fill="rgba(255,255,255,0.12)" />
  <text x="80" y="600" fill="#ffffff" font-size="118" font-family="Arial, sans-serif" font-weight="700">{label}</text>
  <text x="80" y="700" fill="rgba(255,255,255,0.86)" font-size="46" font-family="Arial, sans-serif">Generated by Neurality seed.py</text>
</svg>"""
    path.write_text(svg, encoding="utf-8")


def ensure_seed_media(base_path: Path, filename: str, label: str, start: str, end: str):
    base_path.mkdir(parents=True, exist_ok=True)
    target = base_path / filename
    if not target.exists():
        write_svg(target, label, start, end)
    return target


def seed_database():
    app = create_app()
    with app.app_context():
        ensure_upload_structure(app)
        db.create_all()

        if User.query.count() > 0:
            print("Database already contains users. Seed skipped to avoid duplicates.")
            return

        created_users = []
        for item in SAMPLE_USERS:
            avatar_file = ensure_seed_media(
                app.config["AVATAR_FOLDER"],
                f"{item['username']}.svg",
                item["username"].title(),
                item["accent"][0],
                item["accent"][1],
            )
            user = User(
                username=item["username"],
                email=item["email"],
                bio=item["bio"],
                profile_pic=f"avatars/{avatar_file.name}",
            )
            user.set_password(item["password"])
            db.session.add(user)
            created_users.append(user)

        db.session.commit()

        santa, ginger, blitzen = created_users
        santa.following.append(ginger)
        santa.following.append(blitzen)
        ginger.following.append(santa)
        blitzen.following.append(santa)
        db.session.commit()

        post_specs = [
            (santa, "Workshop lights are up and the first round of gifts is wrapped.", "Santa's Workshop", "#D62828", "#F77F00"),
            (ginger, "Testing cookie batches before tonight's packaging sprint.", "Cookie Test Kitchen", "#6D597A", "#B56576"),
            (blitzen, "Sunrise training run over the ridge before the next route check.", "Blitzen Run", "#355070", "#6D597A"),
        ]

        posts = []
        for idx, (author, caption, label, start, end) in enumerate(post_specs, start=1):
            post_file = ensure_seed_media(
                app.config["POST_FOLDER"],
                f"post_{idx}.svg",
                label,
                start,
                end,
            )
            post = Post(user_id=author.id, image_path=f"posts/{post_file.name}", caption=caption)
            db.session.add(post)
            posts.append(post)

        db.session.commit()

        posts[0].liked_by.append(ginger)
        posts[0].liked_by.append(blitzen)
        posts[1].liked_by.append(santa)
        posts[2].liked_by.append(santa)
        db.session.commit()

        comments = [
            Comment(post_id=posts[0].id, user_id=ginger.id, content="The workshop glow looks perfect tonight."),
            Comment(post_id=posts[0].id, user_id=blitzen.id, content="Route map is ready when you are."),
            Comment(post_id=posts[1].id, user_id=santa.id, content="Saving two boxes for the night shift."),
        ]
        db.session.add_all(comments)

        story_specs = [
            (santa, "story_santa.svg", "Night Shift", "#1D3557", "#457B9D"),
            (ginger, "story_ginger.svg", "Fresh Batch", "#E76F51", "#F4A261"),
            (blitzen, "story_blitzen.svg", "Flight Check", "#2A9D8F", "#264653"),
        ]
        for author, filename, label, start, end in story_specs:
            story_file = ensure_seed_media(app.config["STORY_FOLDER"], filename, label, start, end)
            db.session.add(Story(user_id=author.id, image_path=f"stories/{story_file.name}"))

        db.session.commit()
        print("Neurality sample data created successfully.")


if __name__ == "__main__":
    seed_database()
